let usuarios = [{
        usuario: "coto12",
        nombre: "Alberto Coto",
        correo: "coto@gmail.com",
        contrasenna: "abc123",
        rol: 1,
    },
    {
        usuario: "javier12",
        nombre: "Javier",
        telefono: '80801523',
        correo: "javier@gmail.com",
        contrasenna: "abc123",
        rol: 2,
    },
    {
        usuario: "guille12",
        nombre: "Guillermo",
        telefono: '88450012',
        correo: "guille@gmail.com",
        contrasenna: "abc123",
        rol: 3,
    },
    {
        usuario: "sebas12",
        nombre: "Sebastian",
        telefono: '81235858',
        correo: "sebas@gmail.com",
        contrasenna: "abc123",
        rol: 4,
    },
    {
        usuario: "jim12",
        nombre: "Jim Bolaños Zúñiga",
        telefono: '87352289',
        correo: "jim@gmail.com",
        contrasenna: "abc123",
        rol: 1,
    },
    {
        usuario: "Monica",
        nombre: "Monica Carvajal Perez",
        telefono: '80808888',
        correo: "monica12@gmail.com",
        contrasenna: "abc123",
        rol: 4,
    },
];

// roles 1=> admin 2=>secretari@ 3=>veterinari@ 4=>cliente